version: '3.8'

networks:
  nebula_network:
    name: nebula_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.10.0/24

services:
  nebula_server:
    build:
      context: ../../
      dockerfile: nebula.dockerfile
    ports:
      - 8000:8001
    container_name: nebula_server
    restart: always
    networks:
      - nebula_network
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /var/log/supervisor/
        supervisord -c /nebula/deploy/supervisor.conf
        supervisorctl restart nebula_server
